---
- yum: name=httpd enablerepo=epel state=present
- yum: name=httpd-devel enablerepo=epel state=present
- yum: name=mod_ssl enablerepo=epel state=present 
- service: name=httpd state=restarted enabled=yes

