---
- name: epelのインストール
  command: "yum install -y http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/7/x86_64/e/epel-release-7-9.noarch.rpm"

- name: 基本ソフトのインストール
  yum: name={{ item }} enablerepo=epel state=present
  with_items:
    - openssl-devel
    - readline-devel
    - zlib-devel
    - libcurl-devel
    - sqlite
    - sqlite-devel
    - curl-devel 
    - apr-devel 
    - apr-util-devel
    - gcc 
    - make

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present
  
- name: gemインストール前準備
  yum: name={{ item }} state=present
  with_items:
    - mysql-devel
    - postgresql-devel
    - ImageMagick
    - ImageMagick-devel
    - ruby-devel
    
  
  

