---
- name: php repo install
#  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm state=present
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present
  tags: php

- name: php 本体 install
  yum: name={{item}} state=present enablerepo=remi-php55
  with_items:
    - php
    - php-common
  tags: php

- name: php 本体付属 install
  yum: name=php55 state=present enablerepo=remi-php55
  tags: php


- name: phpmyadmin install
  yum: name=phpMyAdmin state=present enablerepo=remi-php55
  tags: php


#- name: phppgadmin install
#  command: unzip phpPgAdmin.zip -d /usr/share
#  : src=phpPgAdmin dest=/usr/share/ directory_mode=yes owner=ec2-user follow=no mode=644
#  tags: php

- name: php-pgsql install
  yum: name={{item}} state=present enablerepo=remi-php55
  with_items:
    - php-pgsql
  tags: php

