---
- name: php repo install
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present

- name: php main install
  yum: name={{item}} state=present enablerepo=remi-php55
  with_items:
    - php 
    - php-devel 
    - php-mbstring 
    - php-mcrypt 
    - php-mysql 


